#!/bin/bash
# rank_wav_setup.sh — Create regression tests for rank-wav
#
# Creates reg-rs regression tests that exercise the rank-wav audio
# analysis CLI with synthetic WAV files generated by sox.
#
# The setup script creates persistent WAV test fixtures (sine waves,
# noise) in $REG_RS_DATA_DIR/wavs/, then registers regression tests
# that run rank-wav against those fixtures. Because the WAV files
# persist between runs, rank-wav always processes the same input and
# should produce byte-identical output.
#
# Usage:
#   bash tests/regression/rank_wav_setup.sh
#
# Prerequisites:
#   - sox (for generating test WAV files)
#   - reg-rs built (cargo build)
#   - rank-wav built (cd ~/github/sw-cli-tools/rank-wav-rs && cargo build)
#
# Environment:
#   REG_RS_BIN      — path to reg-rs binary (default: ./target/debug/reg-rs)
#   RANK_WAV_BIN    — path to rank-wav binary (default: ~/github/sw-cli-tools/rank-wav-rs/target/debug/rank-wav)
#   REG_RS_DATA_DIR — where to store .tdb files (default: ./work/reg-rs/rank-wav-tests)

set -euo pipefail

REG_RS_BIN="${REG_RS_BIN:-./target/debug/reg-rs}"
RANK_WAV_BIN="${RANK_WAV_BIN:-$HOME/github/sw-cli-tools/rank-wav-rs/target/debug/rank-wav}"
export REG_RS_DATA_DIR="${REG_RS_DATA_DIR:-./work/reg-rs/rank-wav-tests}"
export RUST_LOG="${RUST_LOG:-warn}"
WAVS_DIR="$REG_RS_DATA_DIR/wavs"
WAVS_SUB="$WAVS_DIR/sub"

mkdir -p "$REG_RS_DATA_DIR" "$WAVS_DIR" "$WAVS_SUB"

# Verify binaries exist
if [ ! -x "$REG_RS_BIN" ]; then
  echo "ERROR: reg-rs binary not found at $REG_RS_BIN (run: cargo build)" >&2
  exit 1
fi
if [ ! -x "$RANK_WAV_BIN" ]; then
  echo "ERROR: rank-wav binary not found at $RANK_WAV_BIN" >&2
  exit 1
fi
if ! command -v sox &>/dev/null; then
  echo "ERROR: sox not found (brew install sox)" >&2
  exit 1
fi

echo "=== rank-wav Regression Tests ==="
echo "  reg-rs:    $REG_RS_BIN"
echo "  rank-wav:  $RANK_WAV_BIN"
echo "  data dir:  $REG_RS_DATA_DIR"
echo "  wavs dir:  $WAVS_DIR"
echo ""

# ============================================================
# Generate test WAV fixtures
# ============================================================

echo "--- Generating WAV test fixtures ---"

sox -n -r 44100 -b 16 "$WAVS_DIR/sine_220hz.wav" synth 0.5 sine 220 2>/dev/null
sox -n -r 44100 -b 16 "$WAVS_DIR/sine_440hz.wav" synth 0.5 sine 440 2>/dev/null
sox -n -r 44100 -b 16 "$WAVS_DIR/sine_880hz.wav" synth 0.5 sine 880 2>/dev/null
sox -n -r 44100 -b 16 "$WAVS_DIR/noise.wav" synth 0.5 whitenoise 2>/dev/null
sox -n -r 44100 -b 16 "$WAVS_SUB/deep_tone.wav" synth 0.5 sine 110 2>/dev/null

echo "  Created $(find "$WAVS_DIR" -name '*.wav' | wc -l | tr -d ' ') WAV files"
echo ""

# ============================================================
# Create tests
# ============================================================

create_test() {
  local name="$1"
  local cmd="$2"
  shift 2
  echo "  creating: $name"
  "$REG_RS_BIN" create -t "$name" -c "$cmd" "$@" 2>/dev/null
}

R="$RANK_WAV_BIN"
W="$WAVS_DIR"

NORM_PATH="sed 's|$WAVS_DIR|<WAVS>|g; s|$WAVS_SUB|<WAVS>/sub|g'"

echo "--- Creating tests ---"

# Text output tests
create_test "rank_wav_help" \
  "$R --help 2>&1" \
  --timeout 10 \
  --desc "Help text is stable" \
  --expects "Usage line, flag list"

create_test "rank_wav_version_format" \
  "$R --version 2>&1 | sed 's/[0-9][0-9]*\\.[0-9][0-9]*\\.[0-9][0-9]*/X.Y.Z/g; s/[0-9a-f]\\{7,\\}/HASH/g; s/[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}T[0-9:+.]*)/DATETIME)/g'" \
  --timeout 10 \
  --desc "Version string format (volatile parts masked)" \
  --expects "Version: X.Y.Z with masked hash and build date"

# Table output tests
create_test "rank_wav_table_default" \
  "$R $W 2>&1" \
  --timeout 10 \
  --desc "Default table output (4 files, pleasing sort)" \
  --expects "4-row table ranked by pleasing score"

create_test "rank_wav_table_best" \
  "$R $W -s best 2>&1" \
  --timeout 10 \
  --desc "Table output with best sort mode" \
  --expects "4-row table ranked by best score"

create_test "rank_wav_table_extended" \
  "$R $W -e 2>&1" \
  --timeout 10 \
  --desc "Extended metrics table (rolloff, flatness, crest)" \
  --expects "4-row table with extra columns"

create_test "rank_wav_recursive" \
  "$R $W -r 2>&1" \
  --timeout 10 \
  --desc "Recursive scan finds files in subdirectories" \
  --expects "5-row table including sub/deep_tone.wav"

create_test "rank_wav_recursive_count" \
  "echo non_recursive=\$($R $W 2>&1 | grep -c '|.*wav.*|') recursive=\$($R $W -r 2>&1 | grep -c '|.*wav.*|')" \
  --timeout 10 \
  --desc "Recursive scan finds more files than non-recursive" \
  --expects "non_recursive=4 recursive=5"

# JSON output tests
create_test "rank_wav_json_keys" \
  "$R $W --json 2>&1 | python3 -c \"import sys,json; d=json.load(sys.stdin); print('count='+str(len(d))); print('keys='+','.join(sorted(d[0].keys())))\"" \
  --timeout 10 \
  --desc "JSON output has expected structure (field names, count)" \
  --expects "count=4 and list of field names"

create_test "rank_wav_json_scores" \
  "$R $W --json 2>&1 | python3 -c \"import sys,json; d=json.load(sys.stdin); [print(f'{e[\\\"path\\\"].split(\\\"/\\\")[-1]}:{e[\\\"pleasing_score\\\"]:.3f}') for e in sorted(d, key=lambda x: -x['pleasing_score'])]\"" \
  --timeout 10 \
  -P "$NORM_PATH" \
  --desc "JSON pleasing scores (sorted, 3 decimal places)" \
  --expects "filename:score pairs matching table output"

create_test "rank_wav_json_extended" \
  "$R $W --json -e 2>&1 | python3 -c \"import sys,json; d=json.load(sys.stdin); ext=['spectral_rolloff','spectral_flatness','crest_factor']; print('extended_keys=' + ','.join(k for k in ext if k in d[0]))\"" \
  --timeout 10 \
  --desc "JSON extended metrics include extra fields" \
  --expects "extended_keys=spectral_rolloff,spectral_flatness,crest_factor"

# Edge case tests
create_test "rank_wav_empty_dir" \
  "D=\$(mktemp -d) && $R \"\$D\" 2>&1; echo exit=\$?; rm -rf \"\$D\"" \
  --timeout 10 \
  -P "sed 's|/var/[^ ]*|<TMPDIR>|g; s|/private/var/[^ ]*|<TMPDIR>|g; s|/tmp/[^ ]*|<TMPDIR>|g'" \
  --desc "Empty directory produces 'No WAV files found'" \
  --expects "No WAV files found message, exit=0"

create_test "rank_wav_nonexistent_dir" \
  "$R /nonexistent_dir_xyz 2>&1; echo exit=\$?" \
  --timeout 10 \
  --desc "Nonexistent directory produces error" \
  --expects "Error: Directory does not exist, exit=1"

# Sort order tests
create_test "rank_wav_pleasing_rank_order" \
  "$R $W 2>&1 | grep '| 1 |'" \
  --timeout 10 \
  --desc "Pleasing sort ranks low-frequency sine highest" \
  --expects "Row 1 contains sine_220hz.wav"

create_test "rank_wav_noise_ranks_last" \
  "$R $W 2>&1 | grep '| 4 |'" \
  --timeout 10 \
  --desc "Noise ranks last in pleasing sort" \
  --expects "Row 4 contains noise.wav"

# ============================================================
# Run tests and report
# ============================================================

echo ""
echo "--- Running tests ---"
"$REG_RS_BIN" run -p rank_wav --parallel

echo ""
echo "--- Report ---"
REPORT=$("$REG_RS_BIN" report -p rank_wav -v)
echo "$REPORT"

FAILED=$(echo "$REPORT" | grep -o '[0-9]* failed' | head -1 | grep -o '[0-9]*' | sed 's/^0*//')
PASSED=$(echo "$REPORT" | grep -o '[0-9]* passed' | head -1 | grep -o '[0-9]*' | sed 's/^0*//')

echo ""
if [ "${FAILED:-0}" -gt 0 ]; then
    echo "=== FAILED: ${FAILED} rank-wav test(s) failed ==="
    echo ""
    echo "To see diffs:   REG_RS_DATA_DIR=$REG_RS_DATA_DIR $REG_RS_BIN show -p rank_wav -vv"
    echo "To rebase:      REG_RS_DATA_DIR=$REG_RS_DATA_DIR $REG_RS_BIN rebase -p rank_wav"
    exit 1
elif [ "${PASSED:-0}" -eq 0 ]; then
    echo "=== ERROR: No tests were run ==="
    exit 2
else
    echo "=== PASSED: All ${PASSED} rank-wav test(s) passed ==="
fi
