[package]
name = "reg-rs-report"
version = "0.1.0"
edition = "2024"

[dependencies]
reg-rs-types = { path = "../../../core/crates/types" }
reg-rs-store = { path = "../../../core/crates/store" }
reg-rs-store-rgt = { path = "../../../core/crates/store-rgt" }
reg-rs-runner = { path = "../runner" }
colored = "2.1.0"
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
tinytemplate = "1.2.1"
chrono = "0.4.31"
